server:
  port: 8091

spring:
  application:
    name: DrinaxTracker
  main:
    banner-mode: off
  cloud:
    vault:
      token: 00000000-0000-0000-00000000000
      scheme: http
      application-name: drinaxtracker
      host: 127.0.0.1
      port: 8200
  profiles:
    active: dev
  datasource:
    #url: jdbc:mysql://thor:3306/drinax_tracker
    #username: ${dbusername}
    #password: ${dbpassword}
    url: jdbc:h2:file:/data/drinax_tracker
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-mysql.sql

management:
  endpoints:
    web:
      exposure:
        include: "*"
